# Python, Numpy and Vectorization

## Goal
Review NumPy and Python features used throughout this course.

In [1]:
import numpy as np
import time

## Vectors

### Vector Creation
NumPy gives multiple ways to create vectors — some fill with default values, some with random values, some with your own specific numbers.

In [2]:
a = np.zeros(4)
print(f"a: {a}, size: {a.size}, datatype: {a.dtype}") 
a = np.zeros((4,))
print(f"a: {a}, size: {a.size}, datatype: {a.dtype}")
a = np.random.random_sample(4)
print(f"a: {a}, size: {a.size}, datatype: {a.dtype}")

a: [0. 0. 0. 0.], size: 4, datatype: float64
a: [0. 0. 0. 0.], size: 4, datatype: float64
a: [0.30525846 0.04701476 0.06349188 0.87021434], size: 4, datatype: float64


Some data creation routines do not take a shape tuple as input.

In [3]:
a = np.arange(4.)
print(f"np.arange(4.): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.arange(0,30,3)
print(f"np.arange(4.): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.random.rand(4)
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.): a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.arange(4.): a = [ 0  3  6  9 12 15 18 21 24 27], a shape = (10,), a data type = int64
np.random.rand(4): a = [0.69419655 0.24876048 0.81157259 0.06638963], a shape = (4,), a data type = float64


In [4]:
a = np.array([5,4,3,2])
print(f"np.array([5,4,3,2]) {a} , shape: {a.shape} , Datatype: {a.dtype}")
a = np.array([5.,4,3,2])
print(f"np.array([5.,4,3,2]) {a} , shape: {a.shape} , Datatype: {a.dtype}")

np.array([5,4,3,2]) [5 4 3 2] , shape: (4,) , Datatype: int64
np.array([5.,4,3,2]) [5. 4. 3. 2.] , shape: (4,) , Datatype: float64


### Indexing
Indexing means referring to a single element of an array by its position.

In [5]:
a = np.arange(10)
print(a)
print(f"a[2] {a[2]}")
print(f"a[-1] {a[-1]}")
print(f"a[-2] {a[-2]}")

[0 1 2 3 4 5 6 7 8 9]
a[2] 2
a[-1] 9
a[-2] 8


### Slicing
Slicing creates a subset of an array using start:stop:step, similar to how arange works, but applied to an existing array instead of generating new numbers.

In [6]:
a = np.arange(10)
print(f"a {a}")

c = a[2:8:1]
print(f"c {c}")
#IN slicing ,  the position of each number and its value are exactly the same number. Position 2 holds the value 2
c = a[2:7:2]
print(f"c {c}")

c = a[3:]
print(f"c {c}")

c = a[:7]
print(f"c {c}")

c = a[:]
print(f"c {c}")

a [0 1 2 3 4 5 6 7 8 9]
c [2 3 4 5 6 7]
c [2 4 6]
c [3 4 5 6 7 8 9]
c [0 1 2 3 4 5 6]
c [0 1 2 3 4 5 6 7 8 9]


### Single Vector Operations
Operations you can apply to just one vector at a time — negation, sum, mean, and squaring.

In [7]:
a = np.array([1,3,5,7,9])
print(f"a {a}")

b = -a
print(f"-a {b}")

b = np.sum(a)
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2 : {b}")




a [1 3 5 7 9]
-a [-1 -3 -5 -7 -9]
b = np.sum(a) : 25
b = np.mean(a): 5.0
b = a**2 : [ 1  9 25 49 81]


### Vector-Vector Element-wise Operations
Operations between two vectors, applied position by position.

In [8]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,-3,4])

print(f"binary operators works element wise  {a+b}")

c = np.array([1,2])
try:
    d = c+a
except Exception as e:
    print(f"the error message you see is {e}")

binary operators works element wise  [0 0 0 8]
the error message you see is operands could not be broadcast together with shapes (2,) (4,) 


### Scalar Vector Operations
Multiplying an entire vector by a single number.

In [9]:
a = np.array([1,2,3,4])
b = 5*a
print(f"b {b}")

b [ 5 10 15 20]


### The Dot Product
The dot product multiplies two vectors element-wise, then sums the results into a single number. It's one of the most important operations in this entire course.

In [10]:
def my_dot(a,b):
    x =0
    for i in range(a.shape[0]):
        x = x+a[i]*b[i]
    return x

a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


Let's compare our own version against NumPy's built-in np.dot function.

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape}")

c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape}")

NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = ()
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = ()


### The Need for Speed
NumPy is faster than plain Python loops because it uses vectorized operations under the hood. Let's prove it by timing both approaches on a huge array.

In [12]:
# np.random.seed(1) locks the random number generator to a fixed starting point,
# so the "random" numbers below are the same every time this cell runs.
# The number 1 has no special meaning - any number would work the same way,
# it's just used here so results are repeatable and match the lab example.

np.random.seed(1)
a = np.random.rand(100000)
b = np.random.rand(100000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(f"np.dot(a, b) = {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms")

tic = time.time()
c = my_dot(a, b)
toc = time.time()



print(f"my_dot(a, b) = {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms")

del(a)
del(b)

np.dot(a, b) = 24931.9988
Vectorized version duration: 2.1527 ms
my_dot(a, b) = 24931.9988
loop version duration: 128.2704 ms


### Vector-Vector Operations in Course 1
A quick note on how this applies going forward: training data will be stored as a 2D array (matrix) called X_train, and extracting one row at a time (X[i]) gives you a 1D vector.

In [16]:
x = np.array([[1],[2],[3],[4]])
w = np.array([2])

c = np.dot(x[1], w)
print(f"X[1] has shape {x[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


## Matrices
Matrices are two-dimensional arrays — think of them as a grid of numbers, with rows and columns.

In [18]:
a = np.array([
 [1000,5,10],
 [1500,3,5],
[1200,4,8]
])

### Matrix Creation
The same functions that create vectors also create matrices — you just give them a 2D shape instead of a single number.

In [19]:
a = np.zeros((1, 5))
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((2, 1))
print(f"a shape = {a.shape}, a = {a}")

a = np.random.random_sample((1, 1))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.62164322]]


In [20]:
a = np.array([[5], [4], [3]])
print(f"a shape = {a.shape}, np.array: a = {a}")

a = np.array([[5],
              [4],
              [3]])
print(f"a shape = {a.shape}, np.array: a = {a}")

a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


### Matrix Indexing
Matrices need two indexes to access an element: [row, column].

In [26]:
a = np.arange(6).reshape(-1, 2)
print(f"a.shape: {a.shape}, \na= {a}")

print(f"\na[2,0].shape: {a[2, 0].shape}, a[2,0] = {a[2, 0]}, type(a[2,0]) = {type(a[2, 0])}")

print(f"a[2].shape: {a[2].shape}, a[2] = {a[2]}, type(a[2]) = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape: (), a[2,0] = 4, type(a[2,0]) = <class 'numpy.int64'>
a[2].shape: (2,), a[2] = [4 5], type(a[2]) = <class 'numpy.ndarray'>


### Matrix Slicing
Slicing works on matrices too, using the same start:stop:step pattern, but now for both rows and columns.

In [28]:
# Create a matrix: 20 numbers reshaped into 2 rows, 10 columns each
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

# Row 0 only, then slice columns 2 through 6 within that row -> returns a 1-D vector
print("a[0, 2:7:1] = ", a[0, 2:7:1], ", a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

# All rows (the bare ':'), but only columns 2 through 6 -> returns a 2-D array
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ", a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# Bare ':' for both rows and columns -> returns the entire matrix, unchanged
print("a[:,:] = \n", a[:,:], ", a[:,:].shape =", a[:,:].shape)

# Row 1, all columns, written explicitly -> returns a 1-D vector
print("a[1,:] = ", a[1,:], ", a[1,:].shape =", a[1,:].shape, "a 1-D array")

# Row 1, written without the column part -> same result as above, shorter syntax
print("a[1] = ", a[1], ", a[1].shape =", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] , a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] , a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] , a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] , a[1,:].shape = (10,) a 1-D array
a[1] =  [10 11 12 13 14 15 16 17 18 19] , a[1].shape = (10,) a 1-D array


## Summary
Reviewed NumPy vectors and matrices - creation, indexing, slicing, and vector operations including the dot product. Confirmed vectorization is significantly faster than manual loops.